version: '3'
networks:
  backend:
    driver: bridge
services:
  app:
    build: .
    container_name: uct-mobiperf
    image: staveesh/mobiperf-simulator
    ports:
      - "8080:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend